# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bikebook < Formula
  desc "Agent-first CLI for the BikeBook Workshop API"
  homepage "https://github.com/helopony/bikebook-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.2.0/bikebook_v0.2.0_darwin_amd64.tar.gz"
      sha256 "0807175572034b777a30596efe42db9c4c6dea735b198c67eccf1384e169d201"

      define_method(:install) do
        bin.install "bikebook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.2.0/bikebook_v0.2.0_darwin_arm64.tar.gz"
      sha256 "993c583066cd1df30a989616c0f71e3dc14dfff06e50d1878024e09a743800d7"

      define_method(:install) do
        bin.install "bikebook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.2.0/bikebook_v0.2.0_linux_amd64.tar.gz"
      sha256 "3376ed3d668fc38ddce51cedb5a1fb337aea75ac261b468d40016dc39cc33dba"
      define_method(:install) do
        bin.install "bikebook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.2.0/bikebook_v0.2.0_linux_arm64.tar.gz"
      sha256 "20a706bcec30c634ca5a66195d95fa75296ac4c8b05ac5b84311231f8c62962e"
      define_method(:install) do
        bin.install "bikebook"
      end
    end
  end

  test do
    system "#{bin}/bikebook", "version"
  end
end
