# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bikebook < Formula
  desc "Agent-first CLI for the BikeBook Workshop API"
  homepage "https://github.com/helopony/bikebook-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.1.3/bikebook_v0.1.3_darwin_amd64.tar.gz"
      sha256 "693617c0e8c66ec5d01aded4ac7ad8ed702d07e26751f1669779783e77b55224"

      define_method(:install) do
        bin.install "bikebook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.1.3/bikebook_v0.1.3_darwin_arm64.tar.gz"
      sha256 "5f06d8f15d6d26e6b36cfde66077d0498a8667c63e4980c605b4ae4a44cf73b8"

      define_method(:install) do
        bin.install "bikebook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.1.3/bikebook_v0.1.3_linux_amd64.tar.gz"
      sha256 "b3f0c14874e5662fcc0dc145cd756b3351e0582849688b65b9666df8c6a835a8"
      define_method(:install) do
        bin.install "bikebook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helopony/bikebook-cli/releases/download/v0.1.3/bikebook_v0.1.3_linux_arm64.tar.gz"
      sha256 "13e29a99550f258e61d964c12735ffd9b031dd8725257105c3ff263ab46a60b3"
      define_method(:install) do
        bin.install "bikebook"
      end
    end
  end

  test do
    system "#{bin}/bikebook", "version"
  end
end
